security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        database:
            entity: { class: App:User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: null
            form_login:
                login_path: security_login
                check_path: security_login
            logout:
                path: security_logout
                target: home
            remember_me:
                secret: '%env(APP_SECRET)%'
    access_control:
        - { path: ^/admin, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
