# fly.toml app configuration file generated for robmeijer-co-uk on 2025-04-27T20:36:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'robmeijer-co-uk'
primary_region = 'lhr'

[build]
  dockerfile = 'docker/Dockerfile'
  build-target = 'app'

[deploy]
  strategy = 'rolling'

[env]
  SERVER_NAME = ':80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['app']
