admin_dashboard_index:
    path:     /dashboard
    methods:  [GET]
    defaults: { _controller: 'App\Controller\Admin\DashboardController::indexAction' }

admin_user_edit:
    path:     /user/{id}/edit
    methods:  [GET, POST]
    defaults: { _controller: 'App\Controller\Admin\UserController:editAction' }

admin_user_change_password:
    path:     /user/{id}/change-password
    methods:  [GET, POST]
    defaults: { _controller: 'App\Controller\Admin\UserController:changePasswordAction' }
