<?php

namespace App\Repository;

use App\Entity\Page;
use App\Pagination\Pageable;
use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    use Pageable;

    public function findAllPaginated($page = 1, $limit = Page::LIMIT)
    {
        return $this->paginate($this->createQueryBuilder('p')->getQuery(), $page, $limit);
    }
}
