---
on:
    workflow_call:
jobs:
    staging:
        name: 'Staging'
        runs-on: ubuntu-latest
        concurrency: deploy-group-staging
        environment: Staging
        steps:
            - name: 'Check out code'
              uses: actions/checkout@v4

            - name: 'Set up FlyCTL'
              uses: superfly/flyctl-actions/setup-flyctl@v1

            - name: 'Deploy'
              run: flyctl deploy --buildkit --image-label deployment-$GITHUB_SHA
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    production:
        name: 'Production'
        runs-on: ubuntu-latest
        concurrency: deploy-group-production
        environment: Production
        needs: [ staging ]
        steps:
            - name: 'Check out code'
              uses: actions/checkout@v4

            - name: 'Set up FlyCTL'
              uses: superfly/flyctl-actions/setup-flyctl@v1

            - name: 'Deploy'
              run: flyctl deploy --image registry.fly.io/robmeijer-co-uk:deployment-$GITHUB_SHA
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
