---
name: 'Branch: main'
on:
    push:
        branches: [ 'main' ]
    workflow_dispatch:
jobs:
    code_quality:
        uses: ./.github/workflows/code-quality.yaml
    deploy:
        needs: [ code_quality ]
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
